Rails:
  Enabled: true

Style/IndentationWidth:
  Width: 2

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '{}'
    '%W': '{}'
    '%x': '{}'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/LineLength:
  Max: 100
