AllCops:
  RunRailsCops: true

Style/IndentationWidth:
  Width: 2

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '{}'
    '%W': '{}'
    '%x': '{}'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false
  EnforcedStyle: empty_lines

Metrics/LineLength:
  Max: 100
